### ISSUE TITLE
Roboteam_utils travis broken

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#1030]
/bin/bash: /opt/robotests/roboteam_utils.sh: Permission denied

The command "docker run -v ~/.ccache:/opt/.ccache yuhanuncitgez/roboteamtwente:latest "$TRAVIS_BRANCH" "$TRAVIS_REPO_SLUG"" exited with 126.
cache.2

store build cache

**Comment by Yuhanun** [comment]
Fixed.
