### ISSUE TITLE
Segfault in GetBallRisky.cpp

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#1142]
**Describe the bug**
Roboteam_AI segfaults in GetBallRisky.cpp, line 49 on branch development.

**To Reproduce**
Run with referee and one robot. I clicked force start and it repeatedly happened.

**Expected behavior**
Code that does not segfault?

On ubuntu 20.04

**Comment by Yuhanun** [comment]
Not reproducible for me.

**Comment by timovdk** [comment]
Do you have 1 robot for both teams, or 1 for us and 0 for them @rolfvdhulst ?

**Comment by rolfvdhulst** [comment]
The latter @timovdk , one for us, none for them.

**Comment by timovdk** [comment]
I think that that is the issue, it's looping through none existing enemies. I will have a look on how to fix it, thanks @rolfvdhulst
