### ISSUE TITLE
Make world.cpp more pretty with less duplicates

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#151]
ballhandling currently has a lot of duplicate-ish functionality for both teams. Could be merged, although this may be more work in the future when adding ballsensor

**Comment by ThijsLuttikhuis** [comment]
Also, in utils there is 'LastWorld', we should maybe put roboteam_ai->World into roboteam_utils->LastWorld or put Lastworld into World.

**Comment by rolfvdhulst** [comment]
There is a lot of caution with this, since roboteam_world and roboteam_ai world are two seperate entities, and lastworld has dependencies in robothub and other repositories

**Comment by ThijsLuttikhuis** [comment]
''reeeee''
