### ISSUE TITLE
Some files need some work

### ISSUE THREAD

**Issue by Barisimre** [RoboTeamTwente/roboteam_ai#200]
These are the files that need some rework and the person that seems to be responsible for them

 - Keeper.cpp    @rolfvdhulst 
     There is unreachable code
 -  GoAroundPos.cpp   @rolfvdhulst 
     Needs a type switch and some ordering

**Comment by rolfvdhulst** [comment]
@robverbeek can look at the keeper since the most recent changes were by him ( embedded world pr), if this has a lot of priority. GoAroundPos still needs reallife testing too

**Comment by mrlukasbos** [comment]
control/positionControllers/positioncontrolIncludes.h could be removed and the includes can be placed in the files where they are actually needed. (saves compile time)
