### ISSUE TITLE
Area and existence

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#222]
We thought ball area was broken. It was not; roboteam_ai was not receiving invalid area, because the value was never passed on in roboteam_world. New world_state branch can easily fix this problem, however, we have dependecies in AI that are dependent on this invalid area hack. (See World::getBall() e.g.)

Proposed solution:
Refactor 'existence' back into area.
Remove dependecies in AI
Fix it in world_state

You will likely have to look at roboteam_msgs, roboteam_world, roboteam_AI,roboteam_vision in order to fix this.

**Comment by ThijsLuttikhuis** [comment]
fixed it, existence is not refactored back into area yet though. We could do that after practice tournament.
