### ISSUE TITLE
Velocities in roboteam_world are wrong

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#264]
**Describe the bug**
Sometimes the velocities are a factor of 10^5 or so too small. I have difficulty reproducing the bug. Problem was solved upon restarting roboteam world. I expect it's either in roboteam_world, grSim or roboteam_ai.

**To Reproduce**
??? Restart a million times

**Expected behavior**
It just works like normal?

**Comment by mrlukasbos** [comment]
I just came across this as well. it appears it happens if you restart GrSim while keeping roboteam AI running.

**Comment by rolfvdhulst** [comment]
This bug is in roboteam_world because of time dependencies and will only happen when you restart grSim whilst roboteam_world is running.
