### ISSUE TITLE
Creating a general angle module

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#27]
Should have functionality to reliability calculate absolute angle differences, angular velocity etc.. Currently functionality for this is all over the place in our entire system.
Currently M_PI and other definitions (PI=3.14159) are used through eachother and it's quite messy.
Possibly doing this in roboteam_utils is a good idea so we can also use this consistently in roboteam_vision, roboteam_robothub and other repo's.

**Comment by ThijsLuttikhuis** [comment]
Angle class made in roboteam_utils, not pushed yet - creating a new branch which should have the Angle class without anything else breaking
