### ISSUE TITLE
Defence area avoidance for forces GTP

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#289]

**Comment by ThijsLuttikhuis** [comment]
tried to fix it (branch: feature/improveForcePositionControl), seems like my function is not doing anything, even when setting the values extremely high.. 
I have no idea why, maybe someone else could look at it
->src/control/positionControllers/ForcePosControl.cpp

**Comment by mrlukasbos** [comment]
I can help you with that. although I do not seem to find the branch. did you push?

**Comment by ThijsLuttikhuis** [comment]
Forgot to push, indeed :)

**Comment by mrlukasbos** [comment]
fixed in #309

**Comment by mrlukasbos** [comment]
Since we might not want to use forceGTP that much anymore this issue might be invalidated soon.
