### ISSUE TITLE
Go around ball when passing/attacking

### ISSUE THREAD

**Issue by RobZelluf** [RoboTeamTwente/roboteam_ai#292]
When the attacker has the ball, but is not facing the goal, it most often tries to go through the ball instead of around it when trying to get behind the ball.

The same goes for passing.

**Comment by mrlukasbos** [comment]
This could be pretty easily improved by tweaking the GTP parameters. Set the target about .3 or .5 m behind the position, and `avoidBall = true; ` Should do the trick.

**Comment by RobZelluf** [comment]
That is already what is happening right now

**Comment by RobZelluf** [comment]
This should be fixed in GoToPos

**Comment by ThijsLuttikhuis** [comment]
just set the avoidballdistance smaller than the current distance.. otherwise it is already colliding with the ball and it will just use forces.
