### ISSUE TITLE
Decide where to shoot in attack once

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#433]
Only once, not continuously for every shot. Now we risk oscillation between two different targets, which is bad.

**Comment by mrlukasbos** [comment]
I am not sure if this is a good idea. Sometimes it is really better to reconsider. Maybe we need some heuristic for this as well? (of course when you are almost shooting you should go on with it)

**Comment by rolfvdhulst** [comment]
this is implemented already.
