### ISSUE TITLE
Shot controller with slow-moving balls

### ISSUE THREAD

**Issue by RobZelluf** [RoboTeamTwente/roboteam_ai#459]
It would be too much effort to first take control of a slowly moving ball, so maybe shotcontroller should be able to just immediately shoot these

**Comment by rolfvdhulst** [comment]
Doesn't it already do this?

**Comment by mrlukasbos** [comment]
with balllhandle it should do this up to a large extent

**Comment by ThijsLuttikhuis** [comment]
fixed with ballHandle and ballSensor
