### ISSUE TITLE
geneva state should be checked in publishRobotCommand (if the turn is actually legal) as a last failsafe

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#463]

**Comment by rolfvdhulst** [comment]
maybe instead of having the working geneva boolean we can just make a list of all the working geneva states (so only 3 for non-working bots)?

**Comment by mrlukasbos** [comment]
I think we can assume that it will be either 5 or 1 geneva state(s)
