### ISSUE TITLE
Fix Coach

### ISSUE THREAD

**Issue by ThijsLuttikhuis** [RoboTeamTwente/roboteam_ai#47]
coach has a few things that should not be in there:

 - whichrobothasball should be in world? or controlutils?
 - what the hell is "safelyness"? magic numbers much, and probably not the right way to do it.
 - there should not be a public static variable in coach.. (defencepairs) 
 - imo coach should have a seperate folder (like control), instead of a single file in utilities
 - for the future: fix dangerfinder to work well with the coach

**Comment by Barisimre** [comment]
There are duplicate functions in coach and utils and controlutils. This should be cleaned. The safelyness was just there to test things but it should be removed now. Dangerfinder is crucial for coach and we cant make that much good logic without that.
