### ISSUE TITLE
Fix goToPos implementations

### ISSUE THREAD

**Issue by ThijsLuttikhuis** [RoboTeamTwente/roboteam_ai#48]
there are too many go to posses everywhere,
we should limit these to -> controlGoToPos-folder and (maybe) one single gotopos-skill for when you don't need an explicit skill for going to a position.

**Comment by Barisimre** [comment]
We should also think about the way we name things. There are too many "control", "gotopos", "skil"... keywords around.

**Comment by ThijsLuttikhuis** [comment]
fixed
