### ISSUE TITLE
New Composites

### ISSUE THREAD

**Issue by ThijsLuttikhuis** [RoboTeamTwente/roboteam_ai#50]
It might be a good idea to create a few (no more than 5) new composites which are more intuitive for relatively simple stuff like if/else statements etc - when compared to the current implementation.

**Comment by Barisimre** [comment]
It might be a good idea before we actually write big trees, to think about what we want to express with the behavior trees, what functions will we use the most and what would be intuition. The backbone is relatively universal so adding composite classes should be fine.
