### ISSUE TITLE
Sometimes numTrees has pathpoints with positions that are NaN.

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#503]
very hard to reproduce,  it only happens in some very specific cases. I'm keeping a breakpoint active to hope to figure out what is happening.

**Comment by ThijsLuttikhuis** [comment]
I think this happens since the world refactor #491

**Comment by rolfvdhulst** [comment]
So this happens because of division by 0 in numTrees when the maxVel is set to 0.0 in the halt state.

**Comment by rolfvdhulst** [comment]
should be fixed in #495
