### ISSUE TITLE
Interface ball and Robot display are offset

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#52]
The ball position in the interface is drawn on a different point using drawDataPoints() than it is drawn as natively drawn in the interface. This also goes for robot positions, it seems.

**Comment by mrlukasbos** [comment]
what do you mean? The position for drawing a circle is the top-left corner by default; which is desired behaviour.

**Comment by rolfvdhulst** [comment]
You're right, this was a misunderstanding in intended behavior. I'm closing this issue.
