### ISSUE TITLE
Passcoach makes passes fail too easy

### ISSUE THREAD

**Issue by Barisimre** [RoboTeamTwente/roboteam_ai#537]
There is something like an error where if the pass is too inaccurate the receiver doesn't work. This should also be dependent on ball speed, robot positions and in general be more okay with less accurate passes

**Comment by RobZelluf** [comment]
Can you elaborate? @Barisimre 

Should the passcoach just return success more often, or should it return passes that are more accurate?

**Comment by RobZelluf** [comment]
Or should the receiver fail less quickly, so just continue trying to receive the ball?
