### ISSUE TITLE
Control two teams for simulation

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#56]
**Is your feature request related to a problem? Please describe.**
It would be very useful if we can control two teams (i.e. in simulation). 

At the moment the robotcommands are send to the team indicated by the ROS parameter server. 

**Describe the solution you'd like**
The best way, for now, would be to find out how to run two instances of ROS.

**Describe alternatives you've considered**
We could build it to run two trees simultaneously, but that is certainly not possible because of ROS params.

**Comment by pepijndevos** [comment]
I might be mistaken, but I think this could be as simple as running two instances of `roscore` on a different port, and setting `ROS_MASTER_URI` when launching the code.
