### ISSUE TITLE
IOTest_it_subscribes fails a small percentage of the time.

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#66]
**Describe the bug**
IOTest_it subscribes fails sometimes.

**To Reproduce**
Run IOTest a gazillion times

**Expected behavior**
It should work ALL the time. Might be a ROS problem.

**Comment by mrlukasbos** [comment]
http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers#Transport_Hints this might help

**Comment by Barisimre** [comment]
This seems to be fixed
