### ISSUE TITLE
proto packet definition "dribbler" of "robot command" might be incorrect

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#691]
I did a lookup of the 'dribbler' property in the 'robotCommand' proto definition and I noticed that it was defined as `bool` instead of `int`. I am quite sure it should be an `int`. This is probably a mistake after the ROS refactor.

**Comment by HaicoDorenbos** [comment]
I guess you are right. In the code I see that the dribbler value either gets the value: 0, 27 or 31 assigned. But I will do more close research, before I change it from bool to int

**Comment by mrlukasbos** [comment]
That fixes it. Just do it ;-)

**Comment by HaicoDorenbos** [comment]
With the new merge in roboteam_proto this has been solved
