### ISSUE TITLE
The interface port under settings is not actually adjusting the port we're sending on.

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#703]
We are always sending to port 20011..., even though I am changing it in the interface. (confirmed with prints in robothub)

**Comment by JaroKuiken** [comment]
In SettingsWidget.cpp, out of the 5 'changeX' methods, only changeGrSimIp() is used. The rest is defined, but never used. I think you need to make a QObject::connect to actually 'connect' the method to the interface.

**Comment by Yuhanun** [comment]
This is 2019.

**Comment by JaroKuiken** [comment]
Okay, but is it not still a relevant problem?

**Comment by Yuhanun** [comment]
Nope, we're re-working the UI so this is all obsolete.

**Comment by JaroKuiken** [comment]
Fair enough
