### ISSUE TITLE
Epic: remove globals from the AI

### ISSUE THREAD

**Issue by RobotJesse** [RoboTeamTwente/roboteam_ai#707]
Globals are causing a lot of unpredictable, ugly behaviour

We need to get rid of the globals as soon as possible. Passing worlds by argument, for example. This way we get reproducible, testable behaviour.

Non-exhaustive incomplete list: 

- [ ] World 

- [ ] Field

- [ ] Coaches

- [ ] RobotDealer

Feel free to add to this list if you see any more

**Comment by rolfvdhulst** [comment]
You should probably specify which globals are problematic and what your plan is. This is very vague ;)

**Comment by RobotJesse** [comment]
Yes, good idea. I only know a few, that's why I left it vague. I'll add those I know of. If anyone knows any more, feel free to modify this list!
