### ISSUE TITLE
Recursive role function

### ISSUE THREAD

**Issue by RobotJesse** [RoboTeamTwente/roboteam_ai#708]
Each node needs to know what role it has. Currently this is partially done by blackboards, but desired functionality would be a function in Node, that says:

Node::setRole(std::string role){
      this->role = role
      this->child->setRole(role);
}

This seems like an okay option. This sets everything below the node we are currently at to this role.

If anyone has a different suggestion, please share it :)

**Comment by rolfvdhulst** [comment]
Seems like an ok plan
