### ISSUE TITLE
Stopformation needs to be improved

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#737]
During the robocup we learned we underestimated the importance of the stop formation. During 'STOP' you can prepare your robots for the upcoming state. The current version is already quite decent but can be improved:

- [ ] when the ball is close to our defence area, our defenders enter the defence area. This is risky if there is a free kick for the other team, since they can just hit one of our defenders and it gives us an instant yellow card. 
- [ ] some formation positions are pretty random, for example two positions in the corner near the backline. 
- [ ] there is a segfault if too much robots are detected in the world state
- [ ] The keeper moves pretty far out when the ball is close to the goal (it moves out because with the force model it got pushed into the goal and it couldnt go far enough).

**Comment by JaroKuiken** [comment]
StopFormation no longer exists, although i couldn't find the commit where it was removed
