### ISSUE TITLE
NumTrees not working

### ISSUE THREAD

**Issue by Ratoone** [RoboTeamTwente/roboteam_ai#791]
After the structure refactoring, the path is not constructed properly - the end position is not even part of the path. Consider rewriting the algorithm or implementing a different one

**Comment by rolfvdhulst** [comment]
This surely must have been broken in one of the refactors, no?

Also, I believe sometimes that if the path is too long we only return part of the path towards it and recompute it later, but I am not 100% sure about that. It might be a feature.

**Comment by Ratoone** [comment]
Yeah, but this time it computes only 2 points which are really close to the original robot (as in on top of it), and that's it. Probably I removed some workaround or something

**Comment by Ratoone** [comment]
Solved with #822
