### ISSUE TITLE
There's no world->weHaveRobots()

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#799]

**Comment by emielsteerneman** [comment]
what should this do? Return a boolean? Right now I'm using world->getUs()->empty()

**Comment by RobotJente** [comment]
That's also a solution. Yeah I would expect it to return a boolean

**Comment by mrlukasbos** [comment]
is this resolved?

**Comment by RobotJente** [comment]
Yeah it's fine, it's not really necessary
