### ISSUE TITLE
Control: Refactor control with new world

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#817]
- [x] BallHandlePosControl

- [x] DribbleBackwards

- [x] DribbleForwards

- [x] RotateAroundBall

- [x] RotateWithBall

- [x] Collision

- [x] NumTreePosControl

- [x] PathPoint

- [x] ShotController

- [x] BasicPosControl

- [x] ControlUtils

- [x] PosController

- [x] PositionUtils

- [x] Test if the behaviour is the same

**Comment by timovdk** [comment]
The refactored ControlUtils became NewControlUtils, so a naming refactor will be done after all refactoring is done
