### ISSUE TITLE
Print function

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_ai#819]
I notice that we have a lot of print statements in AI. Some error messages are hard to debug. I propose to make a print() function that helps you print messages in a nice way. then you can see where the print actually comes from, AND you can easily set compiler flags to silence certain types of logs. ( i know these exist for cerr, but having an abstraction here is just nice ;-) ) 

Something like this:

```
void print(std::string className, std::string functionName, std::string message, bool isError) { }
```

**Comment by Ratoone** [comment]
I would even go further and propose using a logging library. You can log to std out, and it already has logging methods for different levels.
