### ISSUE TITLE
UB when getting robot for ID

### ISSUE THREAD

**Issue by rttwente** [RoboTeamTwente/roboteam_ai#823]
UB can happen when the new Leaf::updateRobot() is called, since it sometimes returns an optional robot with nothing in it. 

![UBPNG](https://user-images.githubusercontent.com/57089651/75551123-c00b0100-5a33-11ea-943e-e5cdbdd8bf88.png)

**Comment by mrlukasbos** [comment]
This looks like it creates an empty robotview... I guess it should return std::nullopt instead

**Comment by Yuhanun** [comment]
Actually, std::optional's default constructor is equivalent to the std::nullopt_t constructor

https://en.cppreference.com/w/cpp/utility/optional/optional
