### ISSUE TITLE
AI crashes with manual takeover

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#846]
When running the demo, if manual takeover is selected when the controller is already on, the AI crashes with SigAbrt. Same thing when you turn off the controller and the manual takeover is still enabled.

**Comment by mrlukasbos** [comment]
Can you show the error?

**Comment by RobotJente** [comment]
I will post a picture of it once we are back from the demo. Don't want to reproduce it when people are watching

**Comment by RobotJente** [comment]
Could not reproduce
