### ISSUE TITLE
Function that always returns false

### ISSUE THREAD

**Issue by Yuhanun** [RoboTeamTwente/roboteam_ai#851]
**Describe the bug**
There's a function that always returns 0 in the OffensiveCoach
**To Reproduce**
*Not relevant*

https://github.com/RoboTeamTwente/roboteam_ai/blob/development/src/coach/heuristics/OffensiveScore.cpp#L30

**Comment by RobotJente** [comment]
We will burn this coach

**Comment by Ratoone** [comment]
Closed as the coach died in a pillar of flame
