### ISSUE TITLE
Many PID's are not limited, which causes Robothub to not send a message.

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#86]
**Describe the bug**
The max velocity (so (sqrt(xvel^2+yvel^2)) in a robotcommand should be 8.191 m/s (see robothub). Many skills use PID's (Keeper, Interceptball,Attack, GoToPos, DefendOnRobot,GetBall, Harrass, GoToPosLuth). If these are too high robothub will not send a command. We should build a limiter that tests if a skill is not sending too high commands. This also goes for most of the other things in a robotcommand, although velocity and orientation most commonly are the ones that break.

**Comment by ThijsLuttikhuis** [comment]
maybe fix this in publishrobotcommand OR in robothub, by just limiting it and sending an error message through the (RTT AI) terminal.
