### ISSUE TITLE
Clang 9 linker error

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#863]
**Describe the bug**
When compiling with clang 9, the BT library gives a linker error.
![Screenshot from 2020-03-07 00-06-08](https://user-images.githubusercontent.com/55085110/76129348-81fb7780-6007-11ea-868b-fc0327ecf068.png)

**Comment by Yuhanun** [comment]
You're not linking pthread

```cmake
find_package(Threads REQUIRED)
target_link_libraries(rtt::bt Threads::Threads)
```

**Comment by Yuhanun** [comment]
Wait actually I had this same issue, it's not pthread, my bad:

Just add -fPIC to the flags, worked for me, not sure what a more "clean" solution would be
