### ISSUE TITLE
Update structure tactics

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#880]
- [x] Tactics: reset tactic if the conditions for the tactic to reset are true and the tactic is not in the first state. Reset conditions can be found in the corresponding tactic issue

- [x] Certain tactics are "endtactics", which the role can stay in waiting for all the other roles to finish. The tactics need a boolean member to track this (found in corresponding tactic issue description). Once all roles are in their "endtactic", the play is considered finished

**Comment by Ratoone** [comment]
Wrote #887 for this. Needs some unit tests
