### ISSUE TITLE
Segfault in Hungarian.cpp 

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#889]
Run development with 11 robots in grsim. For the other configs I tried (10, 9, 8, 6) it works fine. Dealer gets stuck in the Hungarian and oscillates between steps 3 and 5 a long time, then segfaults.
![Screenshot from 2020-03-13 01-01-41](https://user-images.githubusercontent.com/55085110/76577610-3f81e100-64c6-11ea-8c47-b08281263e57.png)

**Comment by rolfvdhulst** [comment]
Interesting. I will attempt to investigate on Saturday. This is not our code by source so I might just build the algorithm myself and also document it properly. Can you also make this an issue on roboteam_utils?

**Comment by rolfvdhulst** [comment]
I cannot seem to replicate it unfortunately. This is probably an edge case being missed in the code of the Hungarian.

**Comment by rolfvdhulst** [comment]
If you can replicate it again try to see if you can get the exact call that causes it to fail. Then we can write that as a test.
